version: '3.9'
services:
  nestjs:
    container_name: NestBE_container
    depends_on:
      - mongo_db
    restart: always
    build: .
    ports:
      - "3000:3000"   
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  mongo_db:
    container_name: db_container
    image: mongo   
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
volumes:
 mongo_db: {}